#Requires -Version 5.1
<#
.SYNOPSIS
    Verify git changes are expected before promoting assets to git
    
.DESCRIPTION
    Shows git diff stats, highlights unexpected changes, and helps spot
    accidentally modified or generated files that should stay in artifacts/
    
.EXAMPLE
    .\verify_git_changes.ps1
    
    Shows what's staging/unstaged and flags any unexpected asset files
#>

$ErrorActionPreference = 'Stop'

function Show-GitStatus {
    Write-Host "[*] Git Status Report" -ForegroundColor Cyan
    Write-Host "================================================================================" -ForegroundColor Gray
    
    Write-Host ""
    Write-Host "[OK] Staged changes:" -ForegroundColor Green
    git diff --cached --name-status | ForEach-Object {
        Write-Host "  $_" -ForegroundColor Green
    }
    
    $stagedCount = (git diff --cached --name-only | Measure-Object -Line).Lines
    if ($stagedCount -eq 0) {
        Write-Host "  (none)" -ForegroundColor Gray
    }
    
    Write-Host ""
    Write-Host "[?] Unstaged changes:" -ForegroundColor Yellow
    git diff --name-status | ForEach-Object {
        Write-Host "  $_" -ForegroundColor Yellow
    }
    
    $unstagedCount = (git diff --name-only | Measure-Object -Line).Lines
    if ($unstagedCount -eq 0) {
        Write-Host "  (none)" -ForegroundColor Gray
    }
    
    Write-Host ""
    Write-Host "[*] Untracked files:" -ForegroundColor Magenta
    git ls-files --others --exclude-standard | ForEach-Object {
        Write-Host "  $_" -ForegroundColor Magenta
    }
}

function Check-UnexpectedAssets {
    Write-Host ""
    Write-Host "[SCAN] Checking for unexpected asset changes..." -ForegroundColor Cyan
    Write-Host "================================================================================" -ForegroundColor Gray
    
    $staged = git diff --cached --name-only
    $unstaged = git diff --name-only
    $all = $staged + $unstaged
    
    $warnings = @()
    
    # Check for accidentally modified artifacts
    $artifactChanges = $all | Where-Object { $_ -like "artifacts/*" -and $_ -notlike "artifacts/asset_pipeline_manifest.json" }
    if ($artifactChanges) {
        $warnings += @("artifacts/ should not be committed (keep these as local preview only):")
        $artifactChanges | ForEach-Object { $warnings += "  -> $_" }
    }
    
    # Check for lib/gen changes (should be auto-generated by pipeline.py manifest)
    $codegenChanges = $all | Where-Object { $_ -like "lib/gen/assets.g.dart" }
    if ($codegenChanges) {
        Write-Host "  [OK] lib/gen/assets.g.dart (auto-generated, OK)" -ForegroundColor Green
    }
    
    # Check for spec/config changes
    $specChanges = $all | Where-Object { $_ -like "specs/*" }
    if ($specChanges) {
        Write-Host "  [OK] specs/* (character configs, OK)" -ForegroundColor Green
    }
    
    # Check for runtime asset changes
    $assetChanges = $all | Where-Object { $_ -like "assets/characters/*" -or $_ -like "assets/ui/lottie/*" -or $_ -like "assets/sounds/*" }
    if ($assetChanges) {
        Write-Host "  [OK] assets/* (runtime assets, OK)" -ForegroundColor Green
        $assetChanges | ForEach-Object { Write-Host "    $_" -ForegroundColor Green }
    }
    
    if ($warnings.Count -gt 0) {
        Write-Host ""
        Write-Host "[WARNING] Check these:" -ForegroundColor Yellow
        $warnings | ForEach-Object { Write-Host $_ -ForegroundColor Yellow }
        Write-Host ""
        Write-Host "  Use: git restore --staged <file>" -ForegroundColor Yellow
        Write-Host "   or: git reset HEAD <file>" -ForegroundColor Yellow
    } else {
        Write-Host ""
        Write-Host "  [OK] All changes look good!" -ForegroundColor Green
    }
}

function Show-Summary {
    Write-Host ""
    Write-Host "[*] Summary" -ForegroundColor Cyan
    Write-Host "================================================================================" -ForegroundColor Gray
    
    $stagedCount = (git diff --cached --name-only | Measure-Object -Line).Lines
    $unstagedCount = (git diff --name-only | Measure-Object -Line).Lines
    
    Write-Host ""
    Write-Host "  Staged:   $stagedCount file(s)" -ForegroundColor Green
    Write-Host "  Unstaged: $unstagedCount file(s)" -ForegroundColor Yellow
    
    if ($stagedCount -gt 0 -and $unstagedCount -eq 0) {
        Write-Host ""
        Write-Host "  [OK] Ready to commit!" -ForegroundColor Green
        Write-Host "  git commit -m '<message>'" -ForegroundColor Cyan
    } elseif ($stagedCount -eq 0 -and $unstagedCount -gt 0) {
        Write-Host ""
        Write-Host "  [*] Unstaged changes - review and stage if needed:" -ForegroundColor Yellow
        Write-Host "  git add <file> ..." -ForegroundColor Cyan
    } elseif ($stagedCount -eq 0 -and $unstagedCount -eq 0) {
        Write-Host ""
        Write-Host "  [*] No changes to commit" -ForegroundColor Gray
    }
    
    Write-Host ""
}

# Main
Show-GitStatus
Check-UnexpectedAssets
Show-Summary
